// Auth
export const SET    = 'SET_CURRENT_USER';
export const REMOVE = 'REMOVE_CURRENT_USER';

// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';


//Categories
export const RECEIVE_ROOT_CATEGORIES = 'RECEIVE_ROOT_CATEGORIES'
export const RECEIVE_ALL_CATEGORIES = 'RECEIVE_ALL_CATEGORIES'
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY'
